services:
  notes-app:
    build: .
    # image: ghcr.io/ch-tato/ncc-oprec-2026:latest
    container_name: module_3
    ports:
      - "8880:8880"
    # env_file:
    #   - .env
    volumes:
      - notes_db_data:/app/data
    restart: unless-stopped

volumes:
  notes_db_data:
