services:
  app:
    build: .
    # image: ghcr.io/ch-tato/ncc-oprec-2026:latest
    container_name: module_2
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
